version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  consumer:
    build: .
    command: python processing_worker/consumer.py
    depends_on:
      - rabbitmq
      - django