# Generated by Django 5.2.6 on 2025-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
