# Generated by Django 5.2.6 on 2025-09-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
